### ISSUE TITLE
DYODE V1 dyode_out.py

### ISSUE THREAD

**Issue by pooryasheikh** [EBUJOLD/data-diode#1]
hi, at first thank for this wiki and other information.
i have problem to run dyode_out.py:
[root@CentOSOUT DYODE v1 (full)]# sudo python dyode_out.py
INFO:root:Loading config file
INFO:root:Configuration name : Dyode test
INFO:root:Configuration version : 1.0
INFO:root:Configuration date : 2016-05-04
INFO:root:Dyode input ip : 192.168.1.100 (08:00:27:9e:5d:fb)
INFO:root:Dyode output ip : 192.168.1.150 (08:00:27:9e:5d:fb)
DEBUG:root:Parsing "Partage de fichier 1"
DEBUG:root:Trying to launch a new process for module "Partage de fichier 1"
DEBUG:root:Instanciating a file transfer module :: Partage de fichier 1
DEBUG:root:Waiting for file ...
DEBUG:root:2017-12-03 16:30:17.712871
DEBUG:root:{'in': '/home/pi/in', 'type': 'folder', 'port': 9600, 'out': '/home/pi/out'}
DEBUG:root:9600
DEBUG:root:udp-receiver --nosync --mcast-rdv-addr 10.0.1.1 --interface eth1 --portbase 9600 -f 'manifest_Partage de fichier 1.cfg'
Process Partage de fichier 1:
Traceback (most recent call last):
File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
self.run()
File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
self._target(*self._args, **self._kwargs)
File "dyode_out.py", line 28, in launch_agents
dyode.file_reception_loop(properties)
File "/root/dyode/DYODE v1 (full)/dyode.py", line 44, in file_reception_loop
wait_for_file(params)
File "/root/dyode/DYODE v1 (full)/dyode.py", line 69, in wait_for_file
files = parse_manifest(manifest_filename)
File "/root/dyode/DYODE v1 (full)/dyode.py", line 36, in parse_manifest
for item, value in parser.items('Files'):
File "/usr/lib64/python2.7/ConfigParser.py", line 642, in items
raise NoSectionError(section)

how can i solve it?

**Comment by arnaudsoullie** [comment]
Hello,

Let's not duplicate issues.

@EBUJOLD feel free to take a look at the issue here : https://github.com/wavestone-cdt/dyode/issues/3

Arnaud.
